version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - n 14.16
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - pwd
      - cd pokemanage_front
      - pwd
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: pokemanage_front/build
cache:
  paths:
    - /tmp/node_modules.tar