version: "3"

services:
  react:
    container_name: react
    build:
      context: Dockerfiles
      dockerfile: dev
    volumes:
      - .:/var/www/src
    tty: true
    ports:
      - 3000:3000
