version: "3"

services:
  db:
    container_name: db
    image: postgres:13.2
    # latest
    ports:
      - "6297:6297"
    volumes:
      - django_data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "haljion11"
  api:
    container_name: api
    build: ./src/django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/django:/src
    tty: true
    ports:
      - 8888:8000
    links:
      - db:db
  front:
    container_name: react
    build: ./src/react
    volumes:
      - ./src/react:/src
    tty: true
    ports:
      - 3000:3000
    links:
      - api:api
volumes:
  django_data_volume:
    